export interface Course {
    id: string;
    title: string;
    instructor: string;
    rating: number;
    reviewCount: number;
    students: number;
    duration: string;
    price: number;
    originalPrice?: number;
    category: string;
    level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
    description: string;
    tags: string[];
    lastUpdated: string;
    language: string;
    bestseller?: boolean;
    featured?: boolean;
}

export const courseCategories = [
    "All Courses",
    "Development",
    "Design",
    "Marketing",
    "Business",
    "IT & Software",
    "Personal Development",
    "Photography",
    "Music",
];

export const coursesData: Course[] = [
    {
        id: "1",
        title: "Complete Web Development Bootcamp 2024",
        instructor: "Dr. Angela Yu",
        rating: 4.8,
        reviewCount: 287543,
        students: 845230,
        duration: "52 hours",
        price: 89.99,
        originalPrice: 199.99,
        category: "Development",
        level: "All Levels",
        description: "Learn web development from scratch with HTML, CSS, JavaScript, React, Node.js, and more",
        tags: ["Web Development", "React", "Node.js", "JavaScript"],
        lastUpdated: "December 2024",
        language: "English",
        bestseller: true,
        featured: true,
    },
    {
        id: "2",
        title: "Graphic Design Masterclass - Learn GREAT Design",
        instructor: "Lindsay Marsh",
        rating: 4.9,
        reviewCount: 125430,
        students: 432150,
        duration: "38 hours",
        price: 79.99,
        originalPrice: 179.99,
        category: "Design",
        level: "Beginner",
        description: "Master graphic design with Adobe Photoshop, Illustrator, and InDesign",
        tags: ["Graphic Design", "Photoshop", "Illustrator", "InDesign"],
        lastUpdated: "November 2024",
        language: "English",
        bestseller: true,
    },
    {
        id: "3",
        title: "Digital Marketing Complete Course - 12 Courses in 1",
        instructor: "Rob Percival",
        rating: 4.7,
        reviewCount: 98765,
        students: 328940,
        duration: "45 hours",
        price: 94.99,
        originalPrice: 189.99,
        category: "Marketing",
        level: "All Levels",
        description: "Master digital marketing with SEO, social media, email marketing, and more",
        tags: ["Digital Marketing", "SEO", "Social Media", "Email Marketing"],
        lastUpdated: "December 2024",
        language: "English",
        featured: true,
    },
    {
        id: "4",
        title: "Python for Data Science and Machine Learning Bootcamp",
        instructor: "Jose Portilla",
        rating: 4.9,
        reviewCount: 156789,
        students: 567890,
        duration: "42 hours",
        price: 99.99,
        originalPrice: 199.99,
        category: "Development",
        level: "Intermediate",
        description: "Learn Python, NumPy, Pandas, Matplotlib, Scikit-Learn, and TensorFlow",
        tags: ["Python", "Data Science", "Machine Learning", "AI"],
        lastUpdated: "December 2024",
        language: "English",
        bestseller: true,
    },
    {
        id: "5",
        title: "UI/UX Design Specialization",
        instructor: "Daniel Walter Scott",
        rating: 4.8,
        reviewCount: 87654,
        students: 234567,
        duration: "35 hours",
        price: 84.99,
        originalPrice: 169.99,
        category: "Design",
        level: "Beginner",
        description: "Master UI/UX design with Figma, Adobe XD, and design thinking principles",
        tags: ["UI Design", "UX Design", "Figma", "Adobe XD"],
        lastUpdated: "November 2024",
        language: "English",
    },
    {
        id: "6",
        title: "The Complete Business Strategy Course",
        instructor: "Chris Haroun",
        rating: 4.6,
        reviewCount: 45678,
        students: 189234,
        duration: "28 hours",
        price: 74.99,
        originalPrice: 149.99,
        category: "Business",
        level: "All Levels",
        description: "Learn business strategy, planning, and execution from a top MBA professor",
        tags: ["Business Strategy", "MBA", "Management", "Leadership"],
        lastUpdated: "October 2024",
        language: "English",
    },
    {
        id: "7",
        title: "React - The Complete Guide 2024",
        instructor: "Maximilian Schwarzmüller",
        rating: 4.9,
        reviewCount: 198765,
        students: 678901,
        duration: "48 hours",
        price: 89.99,
        originalPrice: 199.99,
        category: "Development",
        level: "Intermediate",
        description: "Master React with hooks, Redux, Next.js, TypeScript, and more",
        tags: ["React", "Redux", "Next.js", "TypeScript"],
        lastUpdated: "December 2024",
        language: "English",
        bestseller: true,
        featured: true,
    },
    {
        id: "8",
        title: "Photography Masterclass: A Complete Guide to Photography",
        instructor: "Phil Ebiner",
        rating: 4.7,
        reviewCount: 67890,
        students: 245678,
        duration: "32 hours",
        price: 69.99,
        originalPrice: 139.99,
        category: "Photography",
        level: "All Levels",
        description: "Learn photography from beginner to advanced with hands-on projects",
        tags: ["Photography", "Camera", "Lighting", "Editing"],
        lastUpdated: "November 2024",
        language: "English",
    },
    {
        id: "9",
        title: "AWS Certified Solutions Architect - Associate 2024",
        instructor: "Stephane Maarek",
        rating: 4.8,
        reviewCount: 123456,
        students: 456789,
        duration: "40 hours",
        price: 94.99,
        originalPrice: 189.99,
        category: "IT & Software",
        level: "Intermediate",
        description: "Pass the AWS Solutions Architect Associate exam with hands-on practice",
        tags: ["AWS", "Cloud Computing", "DevOps", "Certification"],
        lastUpdated: "December 2024",
        language: "English",
        bestseller: true,
    },
    {
        id: "10",
        title: "Music Production in Logic Pro X - Complete Course",
        instructor: "Tomas George",
        rating: 4.7,
        reviewCount: 34567,
        students: 123456,
        duration: "30 hours",
        price: 79.99,
        originalPrice: 159.99,
        category: "Music",
        level: "Beginner",
        description: "Learn music production, mixing, and mastering in Logic Pro X",
        tags: ["Music Production", "Logic Pro X", "Mixing", "Mastering"],
        lastUpdated: "October 2024",
        language: "English",
    },
    {
        id: "11",
        title: "The Complete Personal Development Course",
        instructor: "TJ Walker",
        rating: 4.5,
        reviewCount: 23456,
        students: 98765,
        duration: "25 hours",
        price: 64.99,
        originalPrice: 129.99,
        category: "Personal Development",
        level: "All Levels",
        description: "Improve your communication, confidence, and leadership skills",
        tags: ["Personal Development", "Communication", "Leadership", "Confidence"],
        lastUpdated: "September 2024",
        language: "English",
    },
    {
        id: "12",
        title: "Advanced CSS and Sass: Flexbox, Grid, Animations",
        instructor: "Jonas Schmedtmann",
        rating: 4.9,
        reviewCount: 145678,
        students: 523456,
        duration: "28 hours",
        price: 84.99,
        originalPrice: 169.99,
        category: "Development",
        level: "Advanced",
        description: "Master modern CSS with Flexbox, Grid, animations, and Sass",
        tags: ["CSS", "Sass", "Flexbox", "Grid"],
        lastUpdated: "November 2024",
        language: "English",
        featured: true,
    },
];
